spring.application.name=api-marketplace
spring.data.mongodb.uri=mongodb+srv://udayb3122:mxLsK5BtEx1m7c4p@cluster0.bfipllz.mongodb.net/marketplace?retryWrites=true&w=majority
app.jwt.secret=Ow8UHZzE/6CfyD3zv2jb4hsgGg7CY9psBaI3x5qfyd8=
app.jwt.expiration=3600000
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=udayb3122@gmail.com
spring.mail.password=ewoy rcfd onya ijce
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.swagger-ui.display-operation-id=true

app.name=Marketplace API
app.version=1.0.0

logging.level.root=INFO
logging.level.com.marketplace=DEBUG
logging.level.org.springframework.security=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n